name: Check

on:
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1

     - name: Install
       run: npm ci
       env:
        HUSKY_SKIP_INSTALL: 1

     - name: Lint
       run: npm run lint
        
     - name: Test
       run: npm run test
       env:
        CI: true

     - name: Build
       run: npm run build
